<a href="https://colab.research.google.com/github/peterphoenix/School-Projects/blob/master/MID_ANN_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Peter Phoenix - 2201735413
Artificial Neural Network LA01

4

Time Series Forecasting adalah suatu proses untuk memprediksi hasil berikutnya dari serangkaian urutan kejadian tertentu. Contoh dari time series forecasting adalah saat memprediksi pasar saham. Jika kita terbiasa melihat harga saham yang naik berhari-hari berturut-turut kemudian turun, maka hal inilah yang akan diprediksi oleh Time Series Forecasting. Berdasarkan data yang diinput sebelumnya, proses ini akan mencari kesamaan dari data tersebut. Tentunya hasil prediksi akan berdasarkan dari pola-pola kejadian yang telah diinput sebelumnya.

Salah satu cara untuk melakukan Time Series Forecasting adalah dengan menggunakan RNN atau Recurrent Neural Network. RNN mirip dengan Feedforward Neural Network namun setiap output yang dikeluarkan bergantung pada perhitungan sebelumnya. Pada RNN, setelah selesai melakukan perhitungan pada hidden layer, hasil tersebut disalin ulang menuju input kemudian dilakukan perhitungan berulang lagi. Oleh karena itu saat menghasilkan output, hasil tersebut bergantung dengan input sekarang dan output yang pernah dihitung sebelumnya. Karena ini juga seluruh input pada RNN bergantung satu sama lain. Salah satu contoh RNN paling simpel adalah Elman RNN dan Jordan RNN.

Berikut dibawah adalah contoh kode mengenai Elman RNN


In [ ]:
import numpy as np
from sklearn import metrics

def nonlin(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)

	return 1/(1+np.exp(-x))
	
data_in = np.array([[1, 0, 0, 0],
            [0, 1, 0, 0],
            [0, 0, 1, 0],
            [0, 0, 0, 1],
            [0, 0, 1, 0],
            [0, 1, 0, 0]])
                
data_out = np.array([[0, 1, 0, 0],
            [0, 0, 1, 0],
            [0, 0, 0, 1],
            [0, 0, 1, 0],
            [0, 1, 0, 0],
            [1, 0, 0, 0]])

data_in=data_in/10
data_out=data_out/10

np.random.seed(1)

alpha = 0.001
mu = 0.0
hidden_layers = 4

weight_in = 2*np.random.random((4,hidden_layers)) - 1
weight_hidden = 2*np.random.random((hidden_layers,4)) - 1


feedback = np.zeros((len(data_in),hidden_layers))
recurrence = 2*np.random.random((hidden_layers,hidden_layers))-1

dataset = np.column_stack((data_in, feedback))
weight_in = np.row_stack((weight_in, recurrence))


old_change0 = np.zeros(weight_in.shape)
old_change1 = np.zeros(weight_hidden.shape)

for j in range(2000000):

    layer_in = dataset
    layer_hidden = nonlin(np.dot(layer_in,weight_in))
    layer_out = nonlin(np.dot(layer_hidden,weight_hidden))

    error_out = data_out - layer_out
    
    if (j% 100000) == 0:
        print ("Epoch:{} Error:{}" .format(j, str(np.mean(np.abs(error_out)))))
        
    delta_out = error_out*nonlin(layer_out,deriv=True)
    error_hidden = delta_out.dot(weight_hidden.T)
    delta_hidden = error_hidden * nonlin(layer_hidden,deriv=True)

    new_change0 = layer_in.T.dot(delta_hidden)
    new_change1 = layer_hidden.T.dot(delta_out)

    weight_hidden += mu * old_change1 + alpha * new_change1
    weight_in += mu * old_change0 + alpha * new_change0

    old_change1 = new_change1
    old_change0 = new_change0
    dataset = np.column_stack((dataset[:,0:4], layer_hidden))

print (layer_out)


Epoch:0 Error:0.45031590411389194
Epoch:100000 Error:0.03878993210718985
Epoch:200000 Error:0.03712522577281616
Epoch:300000 Error:0.036624227311387876
Epoch:400000 Error:0.03639619130557832
Epoch:500000 Error:0.03627443773452596
Epoch:600000 Error:0.036205260695931434
Epoch:700000 Error:0.03616485602554741
Epoch:800000 Error:0.03614091373945748
Epoch:900000 Error:0.03612660310257308
Epoch:1000000 Error:0.03611799768456854
Epoch:1100000 Error:0.03611279609910725
Epoch:1200000 Error:0.036109634017038254
Epoch:1300000 Error:0.03610769711292677
Epoch:1400000 Error:0.036106497349309784
Epoch:1500000 Error:0.0361057415137268
Epoch:1600000 Error:0.036105253179306594
Epoch:1700000 Error:0.03610492609098126
Epoch:1800000 Error:0.03610469621753782
Epoch:1900000 Error:0.036104524956769406
[[0.01707675 0.03323618 0.03385386 0.01656846]
 [0.01751601 0.03381676 0.03424943 0.01661029]
 [0.01661889 0.03259152 0.03272055 0.01582964]
 [0.01674087 0.03298209 0.03341739 0.01640389]
 [0.01661889 0.0325915